name: MyEasySpawn-Home
version: '${project.version}'
main: fr.mouton_redstone.myeasyspawnhome.MyEasySpawnHome
api-version: 1.18
authors: [ Mouton_redstone ]
description: adds /home command
depend:
  - MyEasySpawn

commands:
  sethome:
    description: set your home location
    usage: /<command>
    permission: myeasyspawn.sethome
  home:
    description: teleports you to your home
    usage: /<command>
    permission: myeasyspawn.home

permissions:
  myeasyspawn.home:
    description: allows to teleport to home
    default: true

  myeasyspawn.sethome:
    description: allows to set homes
    default: true