name: MyEasySpawn
version: '${project.version}'
main: fr.mouton_redstone.myeasyspawn.MyEasySpawn
api-version: 1.18
authors: [ Mouton_redstone ]
description: Adds a /spawn command and more

commands:
  spawn:
    description: Teleports you to spawn
    usage: /<command>
  setSpawnCooldown:
    description: Sets the cooldown for the spawn command
    usage:/<command> <time in seconds>